name: push mijengo to production
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploying to Mijengo staging
        uses: garygrossgarten/github-action-ssh@release
        with: 
          command: cd /var/www/mijengo/staging/mijengo && git pull origin main
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
